#! /bin/bash

echo "setting up.....";
echo "Creating TestMate folder at home.....";
echo ".";
echo ".";
mkdir ~/TestMate;

echo "Copying important files from ./src to /home/user/TestMate/ ....."
cp src/{cf.sh,comp.sh,init.py,template.cpp,template.java,batchoutput.sh} ~/TestMate/;
if [ $? -ne 0 ]
then
    echo "Aborting : error";
    exit;
fi
echo "."
echo "copied."

echo "Creating command 'cf' for quick access.....";
echo ".";
echo ".";
if grep -q "alias cf='cd ~/TestMate/; ./cf.sh;';" ~/.bash_aliases
then
    echo "alias already present"
else
    printf "\nalias cf='cd ~/TestMate/; ./cf.sh';" >> ~/.bash_aliases
fi
if [ $? -ne 0 ]
then
    echo "Aborting : error";
    exit;
fi
echo "aliases added...";


echo "Changing permissions of directories...."
echo ".";
echo ".";
chmod -R 777 ~/TestMate/
if [ $? -ne 0 ]
then
    echo "Aborting : error";
    exit;
fi
echo "permissions added."


echo "installing tm-vscode from tm-vscode-0.0.1.vsix"
echo "."
echo "."
code --install-extension tm-vscode-0.0.1.vsix;
if [ $? -ne 0 ]
then
    echo "Aborting : error";
    exit;
fi

echo ".";
echo ".";
echo ".";
echo "Open a new terminal and try the command 'cf'";
